### ISSUE TITLE
Updated Risk Rank database

### ISSUE THREAD

**Issue by lczong** [caozhichongchong/arg_ranker#12]
Thank the authors for this amazing tool.

I saw that the Risk Rank database had been expanded to 12,746 sequences from the official website: https://smile.hku.hk/ARGs/Indexing/riskranking. It's quite amazing. I'm curious if the updated database is publicly available now?

I hope to do some research on top of the database. I will appreciate it if the updated database is available.

**Comment by caozhichongchong** [comment]
Hi lczong,

Thank you for reaching out!

I wanted to let you know that arg_ranker v3.1 has been released, which incorporates the latest SARGv3-S database. 
To update your arg_ranker, simply use the command `pip install arg_ranker --upgrade`. 
Please keep in mind that this update is currently undergoing testing. 
If you have any questions or concerns, don't hesitate to contact me. I'll be happy to help!

Best regards,
Anni

**Comment by lczong** [comment]
Hi Anni,

Thank you so much! I am truly grateful for your response and the subsequent update you made to the tool. It has been incredibly helpful and has made my work much smoother.

On a related note, I was wondering if you could kindly share the details on the 'Enrichment'/'Mobility'/'Presence in Pathogen' information. In the beginning, I thought I could inference the information based on the Rank level. But after I checked the labels in the previous database, I found some 'Rank IV' sequences are not enriched in human-related environments but could also be mobile or even present in pathogens. I think it's very interesting. Therefore, I'd like to ask if it's possible to access the 'Enrichment'/'Mobility'/'Presence in Pathogen' for the updated database.

Thank you once again for your exceptional support!

Best regards,
Lucas

**Comment by caozhichongchong** [comment]
Hi Lucas,

Thank you for reaching out!

Great question.
We are in the process of publishing this information; however, it would take roughly a month before it is fully available.
I'll keep you updated :)

Best regards,
Anni

**Comment by lczong** [comment]
Hi Anni,

Thank you so much for your great effort! I'm looking forward to it!

Best regards,
Lucas

**Comment by lczong** [comment]
Hi Anni,

Any update?

Best regards,
Lucas?

**Comment by caozhichongchong** [comment]
Hi Lucas,

Thank you for reaching out!

Here is the table that might be helpful that my colleagues just shared with me :)
[riskranking_20230601_rankI_263.txt](https://github.com/caozhichongchong/arg_ranker/files/11644636/riskranking_20230601_rankI_263.txt)
My also colleague mentioned that "the [website](https://smile.hku.hk/ARGs/Indexing/riskranking) for public access to risk-ranking information is an old version (generated on 2022 Oct). The new table in this email will be sent to the supervisor for his comments. And hope this new version will be posted on the website soon."

Since the paper is not published, you may cite [SARG v3.0 database](https://www.sciencedirect.com/science/article/pii/S2095809922008062) instead.

Hope it helps!

Best regards,
Anni

**Comment by lczong** [comment]
Hi Anni,

Thank you very much! I genuinely appreciate your kind help! Your work means a lot to the community. And I will properly cite the database. 

Best,
Lucas
