### ISSUE TITLE
About risk hierarchy

### ISSUE THREAD

**Issue by yqy6611** [caozhichongchong/arg_ranker#18]
Hi Anni,

First many thanks for your contribution in AMR risk assessment. It's very useful.

Here I have two questions. The first one is about Rank-IV ARGs. From our metagenomics analysis we found that majority of ARGs were categorized as Rank-IV, and your paper mentioned that as well. We think that zoonotic ARGs may exhibit risks in zoonotic pathogens. What do you think? In your opinion how should we assess the risk of Rank-IV ARGs?

We are planning to integrate your risk scheme into our qPCR detection approach. Do you think whether it's practical? How to differentiate variants via qPCR detection?

Hope to hear from you soon.

Regards,
Eric

**Comment by caozhichongchong** [comment]
Hi Eric,

Thank you for reaching out.
Good questions. 
1) One approach is to download representative zoonotic pathogen genomes and run arg_ranker on those genomes. For ARGs identified within zoonotic pathogen genomes, you may consider them as higher risk.

2) It can be challenging. You can align your qPCR primer sequences with ARG sequences available in [our database](https://github.com/caozhichongchong/arg_ranker/blob/sargv3/arg_ranker/data/SARG.db.fasta). 
If a primer pair matches several ARG sequences that all belong to the same [risk rank](https://github.com/caozhichongchong/arg_ranker/blob/sargv3/arg_ranker/data/ARG_rank.txt), then you may infer that the primer pair quantifies a specific ARG family of the same rank. 
However, if the sequences belong to multiple ranks, designing specific qPCR primers might be necessary.

Hope it's helpful!

**Comment by yqy6611** [comment]
Hi Anni, 

Thanks for your informative reply. 

Let me set an example: we can detect CTX-M genes from metagenome data sampled from marine niches. However, the risk hierarchy covered both Rank-I and Rank-IV for the same subtype of plasmid-harbored CTX-M. How can we interpret the risk in such scenario as marine pathogens are mainly zoonotic.

The SARG database is a protein database. Any suggestions on how we utilize it to design primers for qPCR? 

Thanks very much!
Eric

**Comment by caozhichongchong** [comment]
Hi Eric,

I would split CTX-M subtypes into Rank-I and Rank-IV CTX-M and discuss each separately.

Rank-IV ARGs are not enriched in human-associated samples; however, they can still be mobile and present in pathogens. Expanding the definition of human pathogens to include zoonotic pathogens can elevate Rank II ARGs to Rank I, but not Rank IV to Rank I-III. Our research included only a few number of samples representing environments exposed to animal antibiotics. If you observe a high enrichment of Rank IV ARGs in a broader range of animal-associated samples, it would be possible to re-rank Rank IV ARGs to Rank I-III.

If you identify Rank-I or Rank-IV CTX-M in zoonotic pathogen genomes, particularly when associated with mobile genetic elements like plasmids, you could discuss that Rank-IV CTX-M has potential health risks due to its capacity for enrichment in human- or animal-associated environments. However, this chance may be impacted by the presence of an established Rank-I CTX-M.

Good point! What we did is to map NCBI nt database to the SARG database to identify all nucleotide sequences that represent an ARG protein sequence, and then you can design primers using these nucleotide sequences.

Hope it's helpful!
